### ISSUE TITLE
Turn off nginx access log by default

### ISSUE THREAD

**Issue by somethingnew2-0** [discourse/discourse_docker#120]
Since one page load of discourse causes tens of requests to the server, the nginx access log grows exponentially with the number of users.  For instance, the last log I cleared was 50 GBs in size. 

We are running a somewhat popular discourse [forum](http://forum.ionicframework.com/), but keep running out of space on our host due to nginx access logs filling up the disk.  It seems the log rotation cron job isn't working in our docker container (I'm not sure why).  I turned off the access logs in the nginx.conf in the running container and restarted nginx, so the `/var/log/nginx/access.log` will remain empty.  

Can the nginx access logs be disabled by default or at least have an option from the yml config file to disable them? Thanks

**Comment by rata** [comment]
Just rotate them seems the best. Is the default in all distros and you loose pretty much valuable info (for the majority of people out there I guess). And the disk filling shouldn't be an issue with a rotate script

**Comment by somethingnew2-0** [comment]
Well that is a just solution, and likewise it should be enabled in the docker container by default.  The user setting up discourse on a server shouldn't need to enter the container namespace to do this.

**Comment by rata** [comment]
log rotation is done by default now. So, I guess your issue is fixed (in some other way) ?

**Comment by somethingnew2-0** [comment]
Ah perfect, that works for me. https://github.com/discourse/discourse_docker/commit/5d256035c6c2c8685b8735141539c7e3bf835a74
