### ISSUE TITLE
Unable to mount the containers

### ISSUE THREAD

**Issue by zipeldiablo** [discourse/discourse_docker#124]
which: no docker.io in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)

Failed to create the container ID file: open cids/app_boostrap.cid: permission denied
cat: cids/app_boostrap.cid: No such file or directory

Thing is i'm running core_os wich is docker only environnement so i cannot mount discourse the way you want us to build it, and since we don't have access to dockerfile i cannot tweek mine wich isnt working due to postgres issue :/ (also funny thing is when i google my issue nobody seems to run docker the enterprise way so nobody can help me :/) 
Any chance to get a look at how you configure postgres in the dockerfile?

**Comment by SamSaffron** [comment]
This is a general support issue, can you open it on https://meta.discourse.org
