### ISSUE TITLE
SSH Key generation: 3072 bit?

### ISSUE THREAD

**Issue by dbrgn** [discourse/discourse_docker#129]
Don't you think it would be a good idea to generate SSH keys with 3072 bits by default (`-b 3072`)?

https://github.com/discourse/discourse_docker/blob/master/launcher#L164

**Comment by wmark** [comment]
Although I don't get the reason you linked that line I second your suggestion.

The ENISA recommends 3072b for »RSA-problem–based« Kx and »near term« use.

https://www.enisa.europa.eu/activities/identity-and-trust/library/deliverables/algorithms-key-size-and-parameters-report-2014/at_download/fullReport — page 37 (41 in PDF)

Fun fact: In the industry I work in those key-types are as-good-as banned.

**Comment by dbrgn** [comment]
> Although I don't get the reason you linked that line I second your suggestion.

The codbase has changed in the meantime and I didn't link to a specific version :) My bad.

This was the original line: https://github.com/discourse/discourse_docker/blob/a8b66f980e1c33979970f5930ac146a49c2003c3/launcher#L165

**Comment by envygeeks** [comment]
NIST and ENISA recommend 3072 so use 4096.  Oversizing based on recommendations is a standard security practice.

**Comment by dbrgn** [comment]
+1 on that.

**Comment by SamSaffron** [comment]
been ripping out all the ssh stuff in place of a much simpler `docker exec`
exposing ssh is really only super rarely needed

**Comment by envygeeks** [comment]
Yay, I always found it annoying there was SSH, in all our time with Docker we've never had to use anything but `docker exec -it instance bash` to get in and do whatever we needed without trouble.

**Comment by SamSaffron** [comment]
@envygeeks  you are missing a bit of history here, `./launcher` predates even docker 1.0, afaik `exec` was introduced in 1.2 or 1.3 afaik.

**Comment by envygeeks** [comment]
What you said has no bearing on my generic comment whatsoever.

**Comment by SamSaffron** [comment]
your generic comment, while applicable today, was not applicable at all 8
months ago. "in all our time with Docker we've never had to use anything
but docker exec -it instance bash" in particular we used docker here before
docker exec existed.

**Comment by envygeeks** [comment]
Well if we want to play that way, in all that time (8 months) why did it take so long to clean up your docker image to use new technology?

**Comment by envygeeks** [comment]
I'm out now that we are playing dirty now, so lovely day to you.

**Comment by SamSaffron** [comment]
Jordon, Go, find a mirror, take a bow. Congratulations, you just won the
Internet.

**Comment by envygeeks** [comment]
I'll take my cookie, with tears of being upset.

**Comment by wpp** [comment]
@SamSaffron is right [docker exec was introduced in docker 1.3 (october 2014)].(http://blog.docker.com/2014/10/docker-1-3-signed-images-process-injection-security-options-mac-shared-directories/). A lot of us where using ssh up to that point.

> why did it take so long to clean up your docker image to use new technology?

@envygeeks don't be that guy. You could always have sent a Pull Request and helped out that way.

**Comment by envygeeks** [comment]
@wpp Your main point was never disputed so I don't know why it needs to be reiterated?

**Comment by SamSaffron** [comment]
We ripped all the ssh stuff out, you can mix it in if you wish but general installs don't bother with sshd
