### ISSUE TITLE
Is it required to use Expose rather than any form of --link of some kind?

### ISSUE THREAD

**Issue by chamunks** [discourse/discourse_docker#136]
https://github.com/discourse/discourse_docker I would love to get a container setup going where basically the databases are separate from the web.  That said certain containers obviously could benefit from external exposure like PostgreSQL because I'm trying to hook some external processes into Discourse.  Thats about the only reason I can imagine I'd like to expose ports other than specifically Discourse itself's http/s ports.

**Comment by Blaisorblade** [comment]
Using `--link` is discussed in these topics on meta:

https://meta.discourse.org/t/linking-containers-for-a-multiple-container-setup/20867
https://meta.discourse.org/t/how-to-use-docker-multiple-containers-without-exposing-ports/22283

Is there an open bug here, or can this discussion move to meta.discourse.org and this issue be closed?
