### ISSUE TITLE
data & web_only containers don't link nicely.

### ISSUE THREAD

**Issue by chamunks** [discourse/discourse_docker#139]
When I'm linking I still have to discover the data only container IPAddress via
* docker inspect data |grep IPAddress
Linking should be set in a way where it discovers the IP of the data container on its own potentially or uses [Environment Variables](https://docs.docker.com/userguide/dockerlinks/#environment-variables) somehow to just get the IP of the source container.

I can likely set up some little side script that just runs "docker inspect data |grep IPAddress" then uses sed to remove the leading/trailing characters surrounding the IP.
But ideally you'd want to avoid this I would imagine. 
#3 managed to get me past the build issue where defining the IP address of the data container was an issue.  Though it didn't exactly tell you how to obtain the containers IP which if this is attempting to be idiot friendly is assuming deeper knowledge of how docker links work.  I suppose this explains why we're preferring the old method of linking containers just using port to port communication rather than the half way supported --links

**Comment by thisgeekza** [comment]
This is how you do it:

Your web.yml should have the following entries:

```
  DISCOURSE_DB_HOST: data
  DISCOURSE_REDIS_HOST: data
```

and 

```
#Use 'links' key to link containers together, aka use Docker --link flag.
links:
  - link:
      name: data
      alias: data
```

**Comment by SamSaffron** [comment]
I don't think ./launcher understands `./links` we should add that.

**Comment by SamSaffron** [comment]
I am closing this ... we recently added support for docker_args so you have a way to add linking if needed

**Comment by chamunks** [comment]
Tyvm <3
