### ISSUE TITLE
Docker remote installing over tcp

### ISSUE THREAD

**Issue by mustafaakin** [discourse/discourse_docker#140]
I have my Docker daemon running for other purposes. Since the docker path tries to access the docker as:

```
docker_path=`which docker.io || which docker`
...
  test=`$docker_path info 2> /dev/null`

  if [[ $? -ne 0 ]] ; then
    echo "Cannot connect to the docker daemon - verify it is running and you have access"
    exit 1
  fi
```

Fails and I cannot connect to my docker daemon via TCP.

```
docker_path=`/usr/bin/docker -H tcp://127.0.0.1:4500`
```

Specifying like this fails and causes the following output:
```
./launcher bootstrap app --docker-args -H=tcp://127.0.0.1:4500
Usage: docker [OPTIONS] COMMAND [arg...]
 -H=[unix:///var/run/docker.sock]: tcp://host:port to bind/connect to or unix://path/to/socket to use

A self-sufficient runtime for linux containers.
...
```

Is there a way to add extra args properly? I tried modifying the script but the above should work never the less, but not, what am I doing wrong?

**Comment by SamSaffron** [comment]
Can you try a PR to fix ./launcher here, sounds like you have the technical knowhow.

**Comment by mustafaakin** [comment]
Hi, I can, however it needs to change everywhere Docker is included. We have a --docker-args parameter but it applies for run parameters. We would need a different variable, such as I might also want to protect my docker client with TLS etc. So we need something like --docker-access-args . I'm asking it because I want to be in the same page with you when creatig a PR. Now the following works for me:

```
docker_path=`which docker.io || which docker`
// change to 
docker_path="docker -H 127.0.0.1:4500"
// and delete the following in my case but should not normally:
[ -z $docker_path ] && {
  install_docker
}
```

I confused ` with ", and now understand the ` ` evalutes the expression inside it.

**Comment by Supermathie** [comment]
@mustafaakin Given that this is a custom setup, would it be acceptable to have Docker listening on the Unix socket as well as the TCP socket? You can tell it to do both:

```
       -H,  --host=[unix:///var/run/docker.sock]: tcp://[host:port] to bind or
       unix://[/path/to/socket] to use.
          The socket(s) to bind to in daemon mode specified using one or more
          tcp://host:port, unix:///path/to/socket, fd://* or fd://socketfd.
```

That seems like the most robust approach.

**Comment by mustafaakin** [comment]
Yes, it would be acceptable for me, I even realized if we are deploying via TCP, then those local folders would not mean anything at all. However, I think the remote deployment should also be easy, this way it is impossible to do remote deployment. As I saw from other images, people tend to create data containers for storing data, so it is more portable and you don't need to hassle with individual folders in system. https://docs.docker.com/userguide/dockervolumes/

**Comment by SamSaffron** [comment]
hmm where is this at ?

**Comment by SamSaffron** [comment]
closing cause this is both stale and supported via docker_args anyway.
