### ISSUE TITLE
Launcher not found?

### ISSUE THREAD

**Issue by pennyfx** [discourse/discourse_docker#142]
```
docker@dev:/var/discourse$ ./launcher bootstrap app
sh: ./launcher: not found
docker@dev:/var/discourse$ ls -al
total 43
drwxr-xr-x   11 docker   staff          300 Apr  7 16:48 ./
drwxrwxr-x    9 root     staff          200 Apr  7 16:36 ../
drwxr-xr-x    8 docker   staff          260 Apr  7 16:36 .git/
-rw-r--r--    1 docker   staff           83 Apr  7 16:36 .gitignore
-rw-r--r--    1 docker   staff         7842 Apr  7 16:36 README.md
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 bin/
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 cids/
drwxr-xr-x    2 docker   staff           80 Apr  7 16:36 containers/
drwxr-xr-x   13 docker   staff          280 Apr  7 16:36 image/
-rwxr-xr-x    1 docker   staff        16098 Apr  7 16:36 launcher
drwxr-xr-x    2 docker   staff          120 Apr  7 16:36 samples/
drwxr-xr-x    2 docker   staff           80 Apr  7 16:36 scripts/
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 shared/
drwxr-xr-x    2 docker   staff          260 Apr  7 16:36 templates/
docker@dev:/var/discourse$ 
```

What am I missing here?  Launcher exists and permissions look ok, why isn't it working?

**Comment by SamSaffron** [comment]
no idea, first time I have seen something like this.

**Comment by Supermathie** [comment]
Is it on a noexec filesystem?                                                                                                                                     Does it work with 'sh launcher'? 'sh -x launcher'?                                                                                                                                                                                                                                                                                                                                                                                                                   From: Arron SchaarSent: Tuesday, April 7, 2015 12:58To: discourse/discourse_dockerReply To: discourse/discourse_dockerSubject: [discourse_docker] Launcher not found? (#142)docker@dev:/var/discourse$ ./launcher bootstrap app
sh: ./launcher: not found
docker@dev:/var/discourse$ ls -al
total 44
drwxr-xr-x   11 docker   staff          300 Apr  7 16:48 ./
drwxrwxr-x    9 root     staff          200 Apr  7 16:36 ../
drwxr-xr-x    8 docker   staff          260 Apr  7 16:36 .git/
-rw-r--r--    1 docker   staff           83 Apr  7 16:36 .gitignore
-rw-r--r--    1 docker   staff         7842 Apr  7 16:36 README.md
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 bin/
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 cids/
drwxr-xr-x    2 docker   staff           80 Apr  7 16:36 containers/
drwxr-xr-x   13 docker   staff          280 Apr  7 16:36 image/
-rwxr-xr-x    1 docker   staff        16098 Apr  7 16:36 launcher
drwxr-xr-x    2 docker   staff          120 Apr  7 16:36 samples/
drwxr-xr-x    2 docker   staff           80 Apr  7 16:36 scripts/
-rw-r--r--    1 docker   staff        16098 Apr  7 16:48 sh
drwxr-xr-x    2 docker   staff           60 Apr  7 16:36 shared/
drwxr-xr-x    2 docker   staff          260 Apr  7 16:36 templates/
docker@dev:/var/discourse$ 


What am I missing here?  Launcher exists and permissions look ok, why isn't it working?

—Reply to this email directly or view it on GitHub.

**Comment by pennyfx** [comment]
```
docker@dev:/var/discourse$ sh launcher bootstrap app
launcher: line 63: syntax error: unexpected redirection
docker@dev:/var/discourse$ sh launcher
launcher: line 63: syntax error: unexpected redirection
docker@dev:/var/discourse$ sh ./launcher
./launcher: line 63: syntax error: unexpected redirection
docker@dev:/var/discourse$ 
```

**Comment by SamSaffron** [comment]
no idea what is going on here, is it still the case?

**Comment by Blaisorblade** [comment]
@pennyfx You should try `bash launcher` / `bash -x launcher`, since `launcher` is written for `bash`, not standard `sh`. If that helps, I'm guessing your system's `sh` is not `bash`; for instance, many Debian and Ubuntu systems use `dash` as `/bin/sh` (IIRC, even by default since 2006, see https://wiki.ubuntu.com/DashAsBinSh).

**Comment by LongLiveCHIEF** [comment]
Looks like you're running this from within a base docker image container. This step of the process needs to be run on a full OS, or at the minimum a docker image container that has something like ubuntu as the base layer of the image.  

when you see `docker@host` in front of your prompt, it usually means you're not in a typical Linux operating environment.

@Blaisorblade `sh` will use whatever shell is set as active, or available (usually via `/etc/shells`) regardless if it's `bash` or any other shell.  If `sh` fails, then there isn't a shell available at all.

**Comment by Blaisorblade** [comment]
@LongLiveCHIEF's catch of `docker` is good. The data from @pennyfx is still compatible with `sh` not being `bash` – though the original error is confusing. I agree this report should probably be closed as probably invalid (lacking further info) because this was probably on an unsupported configuration, and probably using bash would have fixed it.

> @Blaisorblade sh will use whatever shell is set as active, or available (usually via /etc/shells) regardless if it's bash or any other shell. 

Nope, I double-checked both through experiments and by Googling, and I stand by my earlier comment. I already gave a link which I think has enough info.

For instance, on my Ubuntu system (14.04 LTS), `/bin/sh` is `dash` and can't run Discourse's launcher, even though the current user (root) has bash as its default shell. `bash ./launcher` and `./launcher` work fine.
```bash
root@kamino:~# ll /bin/sh
lrwxrwxrwx 1 root root 4 Mar  4  2015 /bin/sh -> dash
root@kamino:~# grep root /etc/passwd
root:x:0:0:root:/root:/bin/bash
root@kamino:/var/discourse# sh ./launcher
./launcher: 9: ./launcher: [[: not found
./launcher: 1: ./launcher: Syntax error: redirection unexpected
root@kamino:/var/discourse# bash ./launcher
Usage: launcher COMMAND CONFIG [--skip-prereqs]
[...]
root@kamino:/var/discourse# ./launcher
Usage: launcher COMMAND CONFIG [--skip-prereqs]
[...]
```

See also http://stackoverflow.com/a/5725402/53974 and, again, https://wiki.ubuntu.com/DashAsBinSh.

> If sh fails, then there isn't a shell available at all.

Uh? @pennyfx runs command from some shell, probably Bourne-like and in particular `bash` (guessing from the prompt) — there's just `sh` failing by reporting a syntax error.

I thought the original error could be due to `noexec`; but various shells in that setting give "Permission denied", after `mount none -t tmpfs -o noexec image/`.

**Comment by mpalmer** [comment]
@pennyfx: The error you show in your original message occurs when the file specified in the shebang (on the first line of the file, starting with `#!`).  That would suggest that your system doesn't have `/bin/bash`.  Given @LongLiveCHIEF's observation that you appear to be running `./launcher` from within a docker image itself, perhaps that image doesn't have bash installed?  Alternately, it might be installed, but at an alternate location (such as `/usr/bin/bash`) and there's no symlink from `/bin/bash` to this alternate location.

If you run `which bash`, what is returned?  If it prints nothing, you have no `bash` installed.  If it prints something else, then try `ln -s $(which bash) /bin/bash` and see if that helps the situation.

**Comment by SamSaffron** [comment]
closing this ... totally stale, no response from OP since June 

bootstrapping from inside a container is possible but you would have to mount the docker socket and install docker, its kind of weird to do though. bash does not seem like a crazy dependency for launcher
