### ISSUE TITLE
Special characters in env variables don't always make it into Rails

### ISSUE THREAD

**Issue by j00bar** [discourse/discourse_docker#145]
This is a weird one. You ready?

My database password, randomly generated, ends with a # character. It shows correctly in my app.yml - it shows correctly when I `docker exec -ti app env`. It does _not_ make its way into `Rails.app.config.database_configuration`.

Don't know Ruby well enough to know why.

See: https://meta.discourse.org/t/discourse-docker-aws-bootstrap-talks-to-db-fine-run-doesnt/27464

Oddly, also, the "bootstrap" command that runs `rake db:migrate` had no problem with it.

**Comment by SamSaffron** [comment]
This is a support issue, you are hitting a yaml issue 

this will work:

```
   password: "something#" 
```

In future raise support stuff on https://meta.discourse.org so we can properly track it.
