### ISSUE TITLE
Check for and specify that launcher script requires git >= 1.8

### ISSUE THREAD

**Issue by igravious** [discourse/discourse_docker#146]
I was getting away with git 1.7 unbeknownst to myself.

Recently(?) `launcher` uses `git symbolic-ref --short` where `--short` seems to be at least a 1.8ism.

Also uses `git rev-parse @` where use of `@` as shortcut for `HEAD` is not in git 1.7 either.

Can we do some sanity checking of external tools versions?

**Comment by SamSaffron** [comment]
Sure, I support pre-req tests for git (and better still  reducing the version requirement. )

Simplest thing is to force launcher to use git from inside docker and mount `.` as a volume for various git commands. 

PR to improve this is welcome.

**Comment by coding-horror** [comment]
Ok this is done in https://github.com/discourse/discourse_docker/commit/6828238a9f5201f009fa2dbffd867a9901a59ba9 thanks @pfaffman !
