### ISSUE TITLE
Unattended upgrades not working ?

### ISSUE THREAD

**Issue by rata** [discourse/discourse_docker#149]
Hi,

I've installed discourse the docker way and did the unattended upgrades config as recommended in the guide. But there were updates available and after a few days there, there weren't upgraded.

Is cron running fine for unattended upgrades on the container ?Does it work for you ?

**Comment by SamSaffron** [comment]
are you talking about updates inside the container, that is not implemented
and does not really fit well in a container world.

**Comment by rata** [comment]
Yes, I'm taking about the recommendation here: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md#post-install-maintenance

As you ship a "full" ubuntu LTS image, packages there need security upgrades. I'm doing them in some other way, but wanted to let you know that it seems the recommendation to keep them up to date is not working.

**Comment by SamSaffron** [comment]
the recommendation there is about the host. 

I am torn on doing container upgrades in that way. In general we ship new images if any of the apps in our container need an upgrade.

**Comment by rata** [comment]
Oh, ok. I'm interested in upgrading the container, not the host. I already manage that. Sorry I misunderstood :)

**Comment by SamSaffron** [comment]
closing, assume this is resolved
