### ISSUE TITLE
redis config: isn't it better to configure maxmemmory and lru cache ?

### ISSUE THREAD

**Issue by rata** [discourse/discourse_docker#150]
Like described here: http://redis.io/topics/config (under "Configuring Redis as a cache") or here http://redis.io/topics/lru-cache if redis is used "as a cache and for transient data"[1] woudn't it be more robust to specify a maxmemmory option to avoid OOMs and stuff?

It doesn't seem nice if it crashes[2] (see "What happens if Redis runs out of memory?") and if it's used as a cache and transient data, maybe it makes more sense to specify maxmemory and an evict policy. And it's more robust too :)

Not sure what is a reasonable number (or even calculated as a percentage of the instance is running) because I don't really know how it is used.

What do you think?

Thanks a lot,
Rodrigo

[1]: https://github.com/discourse/discourse
[2]: http://redis.io/topics/faq

**Comment by SamSaffron** [comment]
its not strictly an lru cache as jobs in sidekiq are shipped to redis,
eventually if we have a db backend for delayed jobs we can be more
aggressive.

**Comment by rata** [comment]
But a maxme setting isn't better either ? Or if we fail to queue sidekiq jobs, things won't work fine ?

**Comment by SamSaffron** [comment]
sure its probably better, there is some redis tuning that is needed.

**Comment by rata** [comment]
Do you have any hints on how to estimate this maxmem number ?

And, what does it happen today with discourse if we add this and redis maxmemory is reached ?Will it handle the failures (or evicts) nicely?

**Comment by SamSaffron** [comment]
I am uneasy for this to be an issue opened on Discourse Docker, its a discussion that belongs on meta it is super specific to Discourse and I am not sure I want max mem on redis, it is not needed, lately I did a fair amount of work reducing memory requirements for redis anyway.
