### ISSUE TITLE
Problem with proxies that change certificates

### ISSUE THREAD

**Issue by andrefernandes** [discourse/discourse_docker#158]
Many corporate proxies change the SSL certificate and this breaks git and gem.

There could be an option to provide a URL in order to bootstrap process download a new CA certificate that could be installed in order to be recognized by the setup tools.

**Comment by Supermathie** [comment]
Typically in such an environment servers can be whitelisted to avoid the SSL interception - this is what we'd recommend.

Failing that, the corporate certificate can be added into the base image into the `ca-certificates` bundle. Modifying the base image to add the certificate and then append it to that file should be sufficient.

**Comment by SamSaffron** [comment]
Additionally, in the beginning of the bootstrap you can do whatever prep work you need. Post a guide on https://meta.discourse.org when you figure it out so it can help others.
