### ISSUE TITLE
No support for `--expose`

### ISSUE THREAD

**Issue by Blaisorblade** [discourse/discourse_docker#174]
Using `--expose` rather than `-p` is useful when doing reverse proxying, for instance in combination with https://github.com/jwilder/nginx-proxy.
EDIT: however, `launcher` will never use `--expose`.

**Comment by Blaisorblade** [comment]
I just realized that, out of the box, `launcher ssh` only works if the port is bound as a host port. Instead, it'd be enough to expose the port and figure out the container private IP to connect to it.

**Comment by riking** [comment]
Would exposing sockets work for you?

https://github.com/discourse/discourse_docker/blob/master/templates/web.socketed.template.yml

**Comment by Blaisorblade** [comment]
Thanks for answering, but I fear not.
I must run a reverse proxy in a _separate container_, because it lives in front of Discourse and other 8 different containers. This reverse proxy supports proxying normal sockets (in a plug-and-play way). Moreover, IIUC the code you linked doesn't share those sockets across different Docker containers.

Overall, fixing #175 seems much easier, and fixing this looks cleaner and easier.

**Comment by SamSaffron** [comment]
cool, --expose is now supported via docker args, so closing.
