### ISSUE TITLE
Can't set --docker-args through YAML file

### ISSUE THREAD

**Issue by Blaisorblade** [discourse/discourse_docker#175]
Because of #174, I've ended up having to run:
```
./launcher start info1-discourse --docker-args '--expose 80'
```
but I can't save those extra options in the `info1-discourse.yml` script, which is inconvenient.

I'd like that to be fixed; that is, I'd like general support for arbitrary options. (Not doing that would only work if discourse_docker made sure to wrap every Docker feature, or addressed every use case of every Discourse user — I believe both are unfeasible.)

**Comment by SamSaffron** [comment]
I am fine for you to add a 

"docker_args: some_arbitrary_args" 

into the yml format, should be fairly straight forward. its a ./launcher change.

**Comment by SamSaffron** [comment]
also 

expose: should probably support this somehow ... eg: `expose: 80` should work, PR welcome (as long as it does not break stuff)

**Comment by Blaisorblade** [comment]
Thanks, I've got `docker_args` working, will submit that in the next days.

Re `expose: 80`, I'd propose to support `expose_unpublished: 80` in YAML, since the current `expose:` is a misnomer for `publish:` in Docker terminology. I could refactor the syntax to a correct one, but that'd break existing configs.

In fact, `expose: 80` is already accepted but translates to `-p 80`, that is, `--publish 80`. That's a valid way to *publish* container's port 80 to host's port 80; in Docker exposing and publishing are different concepts, and `discourse_docker` also describes this incorrectly as:
> Expose port 22 inside the container on port 2222 on ALL local host interfaces.

Rationale: "expose" just makes a container port available to other containers (through `--link` or `docker inspect`), while "publish" actually publishes the container port as a host port.
