### ISSUE TITLE
Stateless conatiners and `docker-compose`?

### ISSUE THREAD

**Issue by pierreozoux** [discourse/discourse_docker#180]
Do you plan to migrate to stateless containers and use `docker-compose` in the future?

Just wondering, I think it would be a lot easier to maintain.

Thanks for your work!

**Comment by eriko** [comment]
As far as I can tell the containers are stateless with all the data stored outside in /shared.  At least that is how I have set up my multsite instance.  It looks like there is currently no move to docker-compose in the plans. https://meta.discourse.org/t/install-with-docker-compose/27386  Given the variable ways you can assemble a system with the current 'launcher' I think it will take a good reason to change.  The current setup is in many ways a parallel development to docker-compose and is more fine tuned to discourse.  That said as docker-compose evolves I would not be surprised if a transition happens.  I am just a consumer of discourse and not one of the developers.

**Comment by SamSaffron** [comment]
Yeah... what Erik said :)

**Comment by pierreozoux** [comment]
And what about an official docker image?

(Thanks @eriko for the links and input :) )

**Comment by eriko** [comment]
You probably want to ask this over on https://meta.discourse.org  .  That is where feature requests get asked and answered.
