### ISSUE TITLE
Use docker exec instead of ssh

### ISSUE THREAD

**Issue by philhug** [discourse/discourse_docker#185]
It's not recommended to run ssh in a docker container:
https://blog.docker.com/2014/06/why-you-dont-need-to-run-sshd-in-docker/

instead you can use "docker exec -it containername bash" to get a shell in a running docker image

**Comment by SamSaffron** [comment]
we don't by default, we use exec... 

https://github.com/discourse/discourse_docker/blob/master/launcher#L478
