### ISSUE TITLE
Port `launcher` to POSIX-compatible shell

### ISSUE THREAD

**Issue by fbender** [discourse/discourse_docker#192]
While trying to install Discourse within Docker Machine (ex boot2docker), I SSHed into the Virtualbox VM and followed the cloud installation guide. When trying to bootstrap the Discourse app, I got the same error message as in #142. The issue is that minimal "Docker Host OSes" (e.g. those built on Busybox Distributions like Docker Machine / boot2docker or RancherOS) mostly do not ship with `bash`. Also, Debian opted to replace `bash` with `dash` as the default shell (it still ships with `bash`, though). 

So any of this would not be an issue if the `launcher` script itself would not use `bash` extensions and thus be POSIX compliant and executable by shells like `dash` or the one shipped with busybox. I would appreciate it if you could take a look at this and adapt the script. Thanks a lot!

**Comment by fbender** [comment]
For reference, I followed the tutorial at `https://docs.google.com/document/d/1i2lkCV9RPpckC8xRRb8yeGhj1Jebyha-5OHpFiiaTYg/pub` and could run the bootstrap process after issuing the following command: 

```sh
tce-load -wi bash.tcz
```

**Comment by SamSaffron** [comment]
Simplest way to achieve this would be to run launcher from within our base
image. I know its a bit indirect but totally doable.

**Comment by fbender** [comment]
But that would mean running the base system as a privileged container and having another container inside, no? Or do you mean adapting the script so it can / will run inside the container and not the base system?

**Comment by SamSaffron** [comment]
Since we only need bash and git and docker bins, we could do this from a
very light weight image (probably smaller than 10mb) does not need to run
privileged, it can simply mount the pwd and the docker socket.

**Comment by fbender** [comment]
Yes indeed. Seems a bit overkill, though, don't you think?

**Comment by SamSaffron** [comment]
not really, people are complaining about bash and git issues, so I would
like to resolve it cleanly.

**Comment by almereyda** [comment]
And I was about to ask for supporting `bash_completion.d`. Seems this is the wrong direction (= more integration with bash), though.

**Comment by fbender** [comment]
Another option could be a "build" or "packaging" image that prepares everything needed and puts the generated files into a volume. The build image should be built on a slim image (to allow fs caching) that contains just the necessary runtime to execute the Discourse app. 

After building, a slim container (run from the slim image) is started with that volume included (or the files copied to the volume with a new Dockerfile build if you prefer that). This reduces downtime for rebuilds and allows reducing the `launcher` script to just a couple of lines (that in turn can be run by any POSIX shell) while not requiring to launch a privileged container. Most stuff in the `launcher` script can then just be a Ruby script (there are already a lot of parts calling Ruby anyway) that is executed inside the "build" container (reducing maintenance cost -- because who wants to deal with a complex Bash script anyway).
