### ISSUE TITLE
Allow overriding Hostname (Docker -h/--hostname option)

### ISSUE THREAD

**Issue by fbender** [discourse/discourse_docker#193]
In https://github.com/discourse/discourse_docker/blob/2084bbe7bfb20c3e26c24aaa0ee59e73689fe8a1/launcher#L457, the hostname option for the Docker image is set to `$hostname-$config`. Is there a particular reason for this? 

I'm asking because in my setup, I'd like this to be set to `$hostname`. If you agree, I'll try to post a short Pull Request adding a switch to the config files.

**Comment by SamSaffron** [comment]
Sure, feel free to add an option, just keep current behavior as default
