### ISSUE TITLE
Git not installed during Vagrant Provisioning

### ISSUE THREAD

**Issue by LongLiveCHIEF** [discourse/discourse_docker#196]
git is required as part of the `./launcher bootstrap` process, but is not installed with the optional Vagrant based setup that is described in the [Developing with Vagrant](https://github.com/discourse/discourse_docker#developing-with-vagrant) section.

this causes a failure during bootstraping, whereby the user gets the following message:

```
fatal:unable to access 'https://github.com/SamSaffron/pups.git/': Failed to connect to github.com port 443: 'Connections Refused'.
```

I initially thought this was only because the `HTTP_PROXY` was set, but discovered that `git` was also not installed.

Working on a PR.

**Comment by coding-horror** [comment]
we'll add a git check as part of this too, good idea.
