### ISSUE TITLE
Only HTTP Proxy is configured during Vagrant setup

### ISSUE THREAD

**Issue by LongLiveCHIEF** [discourse/discourse_docker#197]
The [Developing with Vagrant](https://github.com/discourse/discourse_docker#developing-with-vagrant) instructions allow for easier setup if you prefer to use vagrant, however currently the `./launcher bootstrap` command fails if you are behind a proxy.

This is partially due to #196 , but the protocol used when cloning pups is https, but only an http proxy is configured during box provisioning. https://github.com/discourse/discourse_docker/blob/master/Vagrantfile#L27

```
    if ENV["http_proxy"]
      config.vm.provision "shell", inline: <<-EOF
        echo "Acquire::http::Proxy \\"#{ENV['http_proxy']}\\";" >/etc/apt/apt.conf.d/50proxy
        echo "http_proxy=\"#{ENV['http_proxy']}\"" >/etc/profile.d/http_proxy.sh
      EOF
    end
```

Working on PR.

**Comment by SamSaffron** [comment]
cool, PR welcome
