### ISSUE TITLE
Support Docker Hub

### ISSUE THREAD

**Issue by bkerensa** [discourse/discourse_docker#203]
Would be nice to have a discourse docker hub repo so we could use tools like Tutum or other Cloud Orchestration tools to deploy Discourse into the cloud with other apps and scale out.

https://hub.docker.com/
http://tutum.co

**Comment by arrowcircle** [comment]
+1 Current repo is violating docker usage. Docker says we should run 1 process per container, but standalone version uses a lot of processes. Also, there is docker compose now, and launcher is the same tool.

Standalone container is bad idea. Ideally, we should have config with 1 container per process (including sidekiq and nginx containers) and all actual versions images should be released to dockerhub

**Comment by SamSaffron** [comment]
closing this ... please continue the discussion here: https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205
