### ISSUE TITLE
Exit with code 0 if a container is already running

### ISSUE THREAD

**Issue by uppfinnarn** [discourse/discourse_docker#204]
If you attempt to start a container that is already running, it exits with code 1.

This is inconsistent with most service management systems, where attempting to start an already started service simply notes this fact and returns 0. This currently makes it difficult to use the launcher in scripts.

**Comment by fbender** [comment]
This should be `exit 0`: https://github.com/discourse/discourse_docker/blob/0b72000a3cd62cc912081db829821e70e3dce19d/launcher#L430

**Comment by coding-horror** [comment]
ok good idea @fbender I made that change
