### ISSUE TITLE
pngout isn't free software

### ISSUE THREAD

**Issue by jamielinux** [discourse/discourse_docker#207]
Does pngout really have to be included in the Discourse Docker image? Discourse prides itself in being a "100% open source discussion platform"; the Discourse code itself is 100% free, but the single and only recommended way to install Discourse actually includes non-free software.

**Comment by SamSaffron** [comment]
its not there on purpose we will get rid of it.

**Comment by jamielinux** [comment]
Awesome. Thanks Sam! :+1:

**Comment by SamSaffron** [comment]
@zogstrip can you confirm we do not have pngout whitelisted and remove from
the image?

**Comment by ZogStriP** [comment]
@SamSaffron I can confirm we don't have `pngout` whitelisted ;)

https://github.com/discourse/discourse/blob/master/.image_optim.yml#L8

**Comment by SamSaffron** [comment]
@Jamie do a PR to remove it from the image that way next build will not
have it.
