### ISSUE TITLE
Postgres data permission error vagrant

### ISSUE THREAD

**Issue by jvanbaarsen** [discourse/discourse_docker#212]
When I use the Vagrant box to test out the discourse, and then run `./launcher bootstrap app`. I get the error that `/shared/postgres_data` is not owned by the correct user.

When I enter the container to check what user is owning that folder, I see user `900` instead of `postgres`

I'm using OSX as a host system. Anyone else ran into this issue?

**output**
```
I, [2015-12-08T16:33:28.997474 #39]  INFO -- : > HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.3/bin/postmaster -D /etc/postgresql/9.3/main
I, [2015-12-08T16:33:28.998643 #39]  INFO -- : > sleep 5
2015-12-08 16:33:29 UTC FATAL:  data directory "/shared/postgres_data" has wrong ownership
2015-12-08 16:33:29 UTC HINT:  The server must be started by the user that owns the data directory.
```

**Comment by trystant** [comment]
I'm running into it as well, but do not know of any solutions as of yet.

**Comment by jvanbaarsen** [comment]
@trystant I gave up on running it with the mounted folder. I just copy the files over to somewhere else within the vagrant box.

**Comment by jvanbaarsen** [comment]
@coding-horror Why did you close this issue? I don't think a solution was given yet right?

**Comment by pschichtel** [comment]
I have the same problem right now. Is there a solution/workaround available?

**Comment by matthewepler** [comment]
I'm getting the same error after an upgrade to the latest Discourse version:

```
...FATAL: data directory "/shared/postgres_data" has wrong ownership
...HINT:  The server must be started by the user that owns the directory.
```

**Comment by jzinedine** [comment]
Same here!

**Comment by codmpm** [comment]
Same here... anyone has a hint for a fix?

**Comment by zhengjia** [comment]
Ran into the same issue. Had to use the image `ubuntu/trusty64` in vagrant to get it working.
