### ISSUE TITLE
ImageMagick is missing LCMS delegate library

### ISSUE THREAD

**Issue by logankoester** [discourse/discourse_docker#224]
When I pass the user data `avatar_url` and `avatar_force_update` into Discourse from SSO provider, an error response ("Account login timed out, please try logging in again") is sent to the client, and a message like this appears in `unicorn.stderr.log`:

> convert: delegate library support not built-in `/var/www/discourse/tmp/download_cache/b1ce444faac77524a7f269a570daf5d031b1bc8b.jpeg' (LCMS) @ warning/profile.c/ProfileImage/814.

The avatars images are coming from [Gravatar](http://en.gravatar.com/).

If I set `sso_overrides_avatar = false`, then I am able to complete the sign in.

I believe the [**install-imagemagick** script](https://github.com/discourse/discourse_docker/blob/master/image/base/install-imagemagick#L39) should include `--with-lcms` (may have to install the `liblcms` packages, etc to make this work).

**Comment by SamSaffron** [comment]
Are you sure this is happening on latest? 

I am totally fine to add lcms, maybe do a PR but not following how this can be blocking... 

https://github.com/discourse/discourse/blob/master/app/models/user_avatar.rb#L79
