### ISSUE TITLE
Launcher stops & blocks the installation because any host port 80 is in use

### ISSUE THREAD

**Issue by rjd22** [discourse/discourse_docker#229]
I'm running docker on my server and have an exclusive IP for docker that I bind by changing my `app.yml` port config to:

```
expose:
  - "<ip-address>:80:80"   # fwd host port 80   to container port 80 (http)
  - "<ip-address>:2222:22" # fwd host port 2222 to container port 22 (ssh)
```

But docker seems to check if any port 80 is being used on the host and stops installing. Making it impossible to continue without removing the `exit;` from the laucher in the `check_ip` function.

I would recommend fixing this by one of the 2:
- Asking if they want to continue even when port 80 is in use
- Checking the app.yml if an IP has been set in expose and checking port 80 on only the IP

Update:
Changed the title to sound a little bit less "mean".

**Comment by SamSaffron** [comment]
Yeah it should only stop if 80 is set to expose and container is not
running (if you bootstrap while container is running it should not stop)

**Comment by samnazarko** [comment]
Just had a similar issue with multiple IPs on our box serving a variety of HTTPS services. I propose https://github.com/discourse/discourse_docker/pull/231.

**Comment by coding-horror** [comment]
Ok this is resolved since `--skip-prereqs` now skips the ports in use check as well

**Comment by rjd22** [comment]
Thank you for the update @coding-horror
