### ISSUE TITLE
Checks that all SMTP config variables are set applicable for remote SMTP server only

### ISSUE THREAD

**Issue by fuerst** [discourse/discourse_docker#241]
Commit ec8f8b835eec9be93ebe4003492f2dbd027f6aa7 added checks that all SMTP config variables are set (see #237). 

I do use a local SMTP server listening only at the docker0 network interface which does not need authentication. Setting DISCOURSE_SMTP_USER_NAME, DISCOURSE_SMTP_PASSWORD, 
DISCOURSE_SMTP_PORT and DISCOURSE_SMTP_ENABLE_START_TLS is not necessary for such a local szenario. Therefor this checks breaks my current installation. I suggest to remove that checks because they are applicable for remote SMTP server setups only.

**Comment by coding-horror** [comment]
That's a rare setup type from my perspective, so this check is correct. Better to add a command line switch to skip in your case perhaps?

**Comment by coding-horror** [comment]
OK, I see your point, I made it skippable here:

https://github.com/discourse/discourse_docker/commit/e93d165d07e2e07dda3b593301705918b5edfd1c
