### ISSUE TITLE
Unable to rebuild container

### ISSUE THREAD

**Issue by caspivey** [discourse/discourse_docker#251]
\# ./launcher rebuild app
Ensuring launcher is up to date
Fetching origin
Launcher is up-to-date
Stopping old container
\+ /usr/bin/docker stop -t 10 app
app
cd /pups && git pull && /pups/bin/pups --stdin
Already up-to-date.
I, [2016-05-03T14:31:43.474584 #38]  INFO -- : Loading --stdin
/pups/lib/pups/merge_command.rb:45:in 'merge': no implicit conversion of String into Hash (TypeError)
        from /pups/lib/pups/merge_command.rb:45:in 'deep_merge'
        from /pups/lib/pups/cli.rb:21:in 'block in run'
        from /pups/lib/pups/cli.rb:18:in 'each'
        from /pups/lib/pups/cli.rb:18:in 'run'
        from /pups/bin/pups:8:in '\<main>'
358478e0665a4554d941b4bfaa7973138ed9cca98159a830e894caefba12c04b
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one

**Comment by coding-horror** [comment]
can you pull latest and try again? Any info about your environment? I can't repro this.

**Comment by caspivey** [comment]
It was an issue on my end that I didn't spot. For whatever reason vim was inserting a g at the cursor position when I opened a file and it broke one of the comments in the config file which is what was breaking the rebuild process. It is working now that I fixed the broken comment.
