### ISSUE TITLE
cannot run app after build userland BIND: error 443/error 5432/error 80

### ISSUE THREAD

**Issue by dredgerman** [discourse/discourse_docker#254]
Hi, Am running on an Ubuntu server with apache, successfully proxy'd to port 4578 as suggested instead of port 80, however error when running app due to clash with 443 which I have not proxy'd

should I proxy it to 4578 also or is there another solution?

Thanks

`starting up existing container
+ /usr/bin/docker start app
Error response from daemon: driver failed programming external connectivity on endpoint app (6783406f342ff1053e2da84223a8fea088638a11bca4d51ff03940cee): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
Error: failed to start containers: app`

**Comment by dredgerman** [comment]
After installing nginx and successfully getting it running on Port 81, delivering web pages, I have started install of separate web and data containers,

Guess what, no matter what container I try to start something is supposedly listening on that port, I suspect it will do this on every port I use,

```starting up existing container
+ /usr/bin/docker start data
Error response from daemon: driver failed programming external connectivity on endpoint data (aa7196e1e7d5958b83b52e74e3761039fc65f5d7297d97d39bd322b39222ca04): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
Error: failed to start containers: data```

very odd any suggestions have searched and no conclusive answers to this long running problem with docker/discourse, running Ubuntu 12, with apache web servers and nginx running perfectly fine next to one another, need to run docker behind nginx,

netstat on port 5432 produces the following out put
>root@myserver:/var/discourse# netstat -peant | grep ":5432"
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      111        9676        1243/postgres
tcp6      0     0 ::1:5432                :::*                    LISTEN      111        9675        1243/postgres

**Comment by dredgerman** [comment]
Ok so postgres is running on host on 5432, but not sure how to set this up so no clash...?

Any help would be appreciated!

**Comment by dredgerman** [comment]
Am following official docs on GitHub and also https://serversforhackers.com/video/installing-discourse-with-docker, official docs do not work at all, error after error 48 hours trying to install!

**Comment by dredgerman** [comment]
Also by making postgres not exposed to web, comment #5432:5432 in data.yml have successfully bootstrapped and have data running,

however cannot do same for web_only.yml, 

>starting up existing container
+ /usr/bin/docker start sbc_forum
Error response from daemon: driver failed programming external connectivity on endpoint sbc_forum (182234dbf9f4dfb62b9a286f7a8c0aecff186952fd04c458ba5781c8ec09d9d1): Error starting userland proxy: listen tcp 127.0.0.1:81: bind: address already in use
Error: failed to start containers: sbc_forum
root@myserver:/var/discourse#

**Comment by dredgerman** [comment]
Nginx is listening on 81, 
sbc_forum.yml setup as follows:
```expose ports:
127.0.0.1:81:80 
want nginx on 81 in front of docker on 80

**Comment by dredgerman** [comment]
I am working under assumption that expose is in format....
expose ports
host:container....

Is anyone from project able to advise this is a miserable first experience of implementing a piece of software!!  With no support or help....

**Comment by coding-horror** [comment]
We don't do this kind of support here. Check meta.discourse.org.

Did you look at https://meta.discourse.org/t/running-other-websites-on-the-same-machine-as-discourse/17247
