### ISSUE TITLE
Docker links become legacy and can be replaced by user-defined network after 1.9

### ISSUE THREAD

**Issue by fantasticfears** [discourse/discourse_docker#257]
Some docker network changes might be useful for future changes.

Docker 1.9 changes network arch to several drivers. The `link` binding across multi-container installation becomes legacy. https://docs.docker.com/engine/userguide/networking/dockernetworks/ Changes to `Links` are described in the end.

`bridge` mode should be the right type discourse_docker have to use. This allows name discovery across containers automatically. Default `bridge` is based on `docker0` network. But containers can attach to another user-created bridge network. In those bridge, `link` is not working and customized DNS settings can apply.

**Comment by SamSaffron** [comment]
sorry for waiting so long here, what is the exact issue here? not following, can you give me an example?

**Comment by fantasticfears** [comment]
Sorry for my late reply, I was in some troubles. The docker documentation says it may deprecate links at some point.

For example, a multi-container discourse installation, `web` and `data`. It's ok to use `link` now. But a migration to docker container networking may be worthwhile for the future.

In the docker container networking, a bridge network can be created for multi container communication and service discovery in terms of Discourse. And the `link` feature can not be used in docker container networking.

For the above mutli-container discourse example, given a `bridge` network called `discourse_network`:
`docker network create --driver bridge discourse_network`

Then a container can attach to this network:
`docker run --network=discourse_network -itd --name=web discourse`
`docker run --network=discourse_network -itd --name=data discourse`

Since docker 1.10, the docker daemon also works as a DNS for the container and the `discourse_network` is a subnet for all containers attached to. Therefore the `web` and `data` containers can access each other without the `link` feature which Discourse setup used today.

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
