### ISSUE TITLE
discourse/discourse:1.3.0 appears 100MB larger and have many layers

### ISSUE THREAD

**Issue by fantasticfears** [discourse/discourse_docker#258]
https://github.com/discourse/discourse_docker/blob/b16d1acfdd8a06277dab972d3097abbde104a2bf/image/base/Dockerfile

https://hub.docker.com/r/discourse/discourse/tags/

I tried 1.3.0 image. So far so good. At stage server, I have a feeling of fast 👍 😎 

Some feedbacks:

1. Much more `RUN` cause many more layers. If maintainability (readability) is not a concern,
they will have to be as few as `RUN` to reduces the number of layers. Those layers have metadata and have to be fetched independently (could be painful in production).
2. `apt-get clean` happen before the install https://github.com/discourse/discourse_docker/blob/b16d1acfdd8a06277dab972d3097abbde104a2bf/image/base/Dockerfile#L45 

Reference:
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
http://guides.rubygems.org/command-reference/

cc @tgxworld

**Comment by fantasticfears** [comment]
Some du -h after bootstrap with `new.postgres.template.yml`. Might not be helpful.

```bash
$ du -h --max-depth=1 /
1.4M	/tmp
4.3M	/etc
998M	/usr
36K	/run
23M	/root
826M	/var
28M	/lib
328K	/pups
48K	/home
4.0K	/src
```

```bash
$ du -h --max-depth=1 /usr/
192M	/usr/share
484M	/usr/lib
215M	/usr/local
4.0K	/usr/etc
6.0M	/usr/sbin
71M	/usr/bin
32M	/usr/include
4.0K	/usr/src
4.0K	/usr/games
```

```bash
$ du -h --max-depth=2 /var/
746M	/var/www/discourse
8.0K	/var/www/html
746M	/var/www
252K	/var/nginx/cache
256K	/var/nginx
564K	/var/backups
12K	/var/spool/cron
4.0K	/var/spool/rsyslog
20K	/var/spool
23M	/var/lib/apt
112K	/var/lib/nginx
18M	/var/lib/dpkg
8.0K	/var/lib/haproxy
37M	/var/lib/postgresql
12K	/var/lib/sgml-base
8.0K	/var/lib/dbus
12K	/var/lib/locales
8.0K	/var/lib/monit
12K	/var/lib/xml-core
4.0K	/var/lib/git
4.0K	/var/lib/supervise
92K	/var/lib/ucf
4.0K	/var/lib/redis
4.0K	/var/lib/python
8.0K	/var/lib/sudo
36K	/var/lib/ghostscript
8.0K	/var/lib/vim
192K	/var/lib/systemd
4.0K	/var/lib/dhcp
28K	/var/lib/pam
4.0K	/var/lib/initscripts
4.0K	/var/lib/insserv
4.0K	/var/lib/update-rc.d
4.0K	/var/lib/urandom
4.0K	/var/lib/misc
78M	/var/lib
12K	/var/cache/apt
24K	/var/cache/ldconfig
1.6M	/var/cache/debconf
108K	/var/cache/fontconfig
8.0K	/var/cache/postgresql
1.8M	/var/cache
12K	/var/log/unattended-upgrades
12K	/var/log/apt
48K	/var/log/nginx
92K	/var/log
4.0K	/var/tmp
4.0K	/var/mail
4.0K	/var/opt
4.0K	/var/local
826M	/var/
```

**Comment by SamSaffron** [comment]
The layers are a non issue, I squash the image prior to pushing, but I will
look at the extra bloat.

**Comment by SamSaffron** [comment]
I improved this some to:

```

discourse/base        1.3.0               671fc54b23e1        3 minutes ago       872.1 MB
discourse/base        1.0.17              f703ffd7ec6e        12 weeks ago        829 MB
```

But I still need to add phantom back in which will add 20MB or so.  I really can not shave that much more off the image without risking breaking stuff. new ubuntu has icu libraries which take up more space

**Comment by fantasticfears** [comment]
Thanks for the effort! So those bytes have to be there :) Close the issue if you want.

Got a visual tools for layers. discourse/discourse:1.0.17 has some problems on their end.
https://imagelayers.io/?images=discourse%2Fdiscourse:1.0.16,discourse%2Fdiscourse:1.3.0,discourse%2Fbase:1.0.16,discourse%2Fbase:1.3.0

And ICU libraries are in place which are quite good. I planned supporting some checks by combining ICU. System library can just saves some complication.
