### ISSUE TITLE
smtp_openssl_verify_mode should be configurable

### ISSUE THREAD

**Issue by dachary** [discourse/discourse_docker#263]
config/environments/production.rb has
<pre>
    settings[:openssl_verify_mode] = GlobalSetting.smtp_openssl_verify_mode if GlobalSetting.smtp_openssl_verify_mode
</pre>
should be configurable in discourse_docker/samples/standalone.yml with
<pre>
DISCOURSE_SMTP_OPENSSL_VERIFY_MODE=false
</pre>

**Comment by dachary** [comment]
It is specially useful when setting up a test instance and the SMTP server is configured on the docker to not match 172.17.0.1

**Comment by xfalcox** [comment]
DISCOURSE_SMTP_OPENSSL_VERIFY_MODE on envs key will do this.
