### ISSUE TITLE
./launcher rebuild app

### ISSUE THREAD

**Issue by KonishiLee** [discourse/discourse_docker#265]
FAILED
--------------------
Pups::ExecError: cd /var/www/discourse && su discourse -c 'bundle install --deployment --verbose --without test --without development' failed with return #<Process::Status: pid 299 exit 5>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"bundle_exec", "cmd"=>["su discourse -c 'bundle install --deployment --verbose --without test --without development'", "su discourse -c 'bundle exec rake db:migrate'", "su discourse -c 'bundle exec rake assets:precompile'"]}
e9547ecf5f72eb03e82ac987779b6727f7a136645b2d2227411210256e3cb86f
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
root@iZ28g865540Z:/var/discourse# llllllllllllllllllllllllcd /var/www/discourse && su discourse -c 'bundle install --deployment --verbose --without test --without development

**Comment by xfalcox** [comment]
This could be caused by a intermittent problem with rubygems server.

Could not reproduce on latest. Please open another issue if it still affecting you.
