### ISSUE TITLE
launcher enter documentation still mentions nsenter

### ISSUE THREAD

**Issue by palant** [discourse/discourse_docker#268]
The `launcher` command still displays the following help text:

> enter:      Use nsenter to get a shell into a container

`nsenter` is [no longer being used](https://github.com/discourse/discourse_docker/commit/30835a52bd724875fcea9c36ff686c0a4eb568e5). The help text should be adjusted to explain functionality rather than implementation.

**Comment by SamSaffron** [comment]
Sure a PR to clean up would be mighty fine
