### ISSUE TITLE
launcher rebuild updates the script

### ISSUE THREAD

**Issue by njt1982** [discourse/discourse_docker#271]
This is a follow on from https://github.com/ruby-bench/ruby-bench-suite/issues/42#issuecomment-234268318

When running the launcher rebuild, the script automatically pulled the latest version of itself from github. This had some very undesirable knock on consequences.

1) The base images changed to a MUCH newer version. This caused a newer version of Ruby to be used which, in turn, stopped Discourse working (2.0.0 vs 2.3.0).
2) As we were using the postgres template, (not specifically postgres 9.3), this caused the database files to all get upgraded to 9.5.

IMHO when you rebuild it should rebuild from whatever you have checked out. It should not update itself. That should either be a separate command on launcher or just left up to a human to to a git pull/checkout. A rebuild should just rebuild; why does a rebuild need to ensure launcher is running the latest version? This is particularly hard to deal with as there are no tagged releases so we cant even checkout a fixed version of stay on it until we can test a specific launcher on staging somewhere else. If this functionality is intended to be kept, can I request it is changed to "opt in"? Have an option you pass to rebuild such as `--with-update`?

In our case, on production, we needed to rebuild due to kernel changes from the hypervisor/host updates. Without reading all 700 lines of the launcher script, it was not immediately obvious that a rebuild would indeed make so many critical changes.

**Comment by xfalcox** [comment]
For having a more powerful control over versions and such, I recommend saving a working `docker image` (maybe publish it to a private docker hub) and working with it.

This script is aimed for non-power users, who just want a simple command to keep their forums working.

Also, we bumped ruby version a year after, and having 100% sure that Discourse worked in the latest ruby. We ran tests against 2.3 for a while and bumped only after it worked. Did you used to run other stuff inside the Discourse container?
