### ISSUE TITLE
docker-setup and netstat

### ISSUE THREAD

**Issue by Pablohn26** [discourse/discourse_docker#274]
When I am following [next instructions](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md#edit-discourse-configuration) on CentOS 7 I get this warning 

>[root@host discourse]# ./discourse-setup
>./discourse-setup: line 144: netstat: command not found
>./discourse-setup: line 144: netstat: command not found

because netstat is not installed on CentOS 7 (it is deprecated in favour of the iproute2).

I am not sure if it affects to port detection or not

**Comment by xfalcox** [comment]
The `./discourse-setup` is aimed at people who aren't familiar with servers, command line and config files.

So it tries to make setup easier as possible for the common case.

For more advanced users, like the ones who aren't following the guide and using the recommended Ubuntu LTS, we recommend manually editing the YAML file and bootstrapping manually.

However, we can review a PR that makes this part of the script more compatible with other distros while keeping Ubuntu LTS compatibility.
