### ISSUE TITLE
NGINX reports configuration fail inside container

### ISSUE THREAD

**Issue by ararunaufc** [discourse/discourse_docker#281]
I ran through the official tutorial to setup Discourse with the docker option.

After everything done, despite having no signs of errors, the server does not come up. Just to emphasize: I only followed the steps in the tutorial, nothing else.

I entered the container and asked NGINX to do a configtest and it reported a failure. I'm not used to NGINX or anything related to it or docker yet, so I cannot report further than this.

Hope you can solve this, as I was really looking forward to testing Discourse.
Thank you.

**Comment by SamSaffron** [comment]
sorry, this is not really the place for these kind of questions, can you try on https://meta.discourse.org ?

**Comment by ararunaufc** [comment]
Well, I think it is a bug, since it is like this right after installation. It's not acting as promissed.

**Comment by ararunaufc** [comment]
Something else I found: the `sites.enabled` folder is empty and the `sites.available` has only the default site file. Is this correct? (Just for me to be sure).

**Comment by ararunaufc** [comment]
Oh, I figured out what it was. Isuues with the Let's Encrypt certificate were preventing NGINX to run.

Sorry.
