### ISSUE TITLE
Dokku compatibility

### ISSUE THREAD

**Issue by PatWie** [discourse/discourse_docker#282]
Deploying this app with a simple Dockerfile would help to use discourse right out from dokku.

**Comment by xfalcox** [comment]
You can create a local image using the `./launcher` tool, publish the resulting Docker image and use it elsewhere.

For more discussion about it see here: https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205?u=falco
