### ISSUE TITLE
[launcher cleanup] df: ‘/var/lib/docker’: No such file or directory

### ISSUE THREAD

**Issue by Pablohn26** [discourse/discourse_docker#284]
## Description

Finishing the clean up, I get this error
> df: ‘/var/lib/docker’: No such file or directory

My _Docker Root Dir_ is changed but seems process does not follow it, just go to default _Docker Root Dir_ (/var/lib/docker/)

Also "bytes free" number is not showed. 

## How to reproduce

Change _Docker Root Dir_
Launch the clean up

## What do you expect

No error. 

## What happened instead

> df: ‘/var/lib/docker’: No such file or directory
> Finished Cleanup (bytes free )

## Software:

- bash version: GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
- OS version: Debian 8.5
- docker version: Docker version 1.12.1, build 23cf638

## Full backtrace

```/var/discourse/launcher cleanup

The following command will
- Delete all docker images for old containers
- Delete all stopped and orphan containers

Are you sure (Y/n): y
df: ‘/var/lib/docker’: No such file or directory
Starting Cleanup (bytes free )
Unable to find image 'samsaffron/docker-gc:latest' locally
latest: Pulling from samsaffron/docker-gc

0f4d770cd333: Pull complete 
a3ed95caeb02: Pull complete 
6a2ea02ca5be: Pull complete 
bc4c30afebbb: Pull complete 
Digest: sha256:1efd5febba28f881c815c37005b09c67fce0fa62d583b82790b0a0fe82cad999
Status: Downloaded newer image for samsaffron/docker-gc:latest
df: ‘/var/lib/docker’: No such file or directory
Finished Cleanup (bytes free )

```

**Comment by Pablohn26** [comment]
It seems [here](https://github.com/discourse/discourse_docker/blob/master/launcher#L340) _DockerRootDir_ is harcoded (`/var/lib/docker`), so that is a problem where it is not by default. I have been looking how to address this problem and seems _DockerRootDir_ is not always displayed with docker info (even with docker -D info), so my best approach is to get it with next command:

> curl -s --unix-socket /var/run/docker.sock http:/info | jq '.DockerRootDir'

Not sure if a Pull Request with this change would be accepted since it is using docker API and an external package (`jq`)

**Comment by xfalcox** [comment]
Yeah, adding a dependency just for that doesn't looks good.

I get a entry `Docker Root Dir: /var/lib/docker` on `docker info` on `1.12.2`. Is it working for you now?

**Comment by Pablohn26** [comment]
Again
> df: ‘/var/lib/docker’: No such file or directory

My docker root dir is ` Docker Root Dir: /repos/var/lib/docker`. Also docker 1.12.2. As I said, that path is harcoded [here](https://github.com/discourse/discourse_docker/blob/master/launcher#L379)

Thanks for your support.

**Comment by xfalcox** [comment]
Sorry for not making my self clear.

I was asking if as Docker 1.12.2 `docker info` is getting always displayed for you.

**Comment by xfalcox** [comment]
We are open for a PR that doesn't bring any new deps.
