### ISSUE TITLE
boot2docker: Disaster after reboot, discourse data lost

### ISSUE THREAD

**Issue by digitalfredy** [discourse/discourse_docker#285]
Hello guys

When I started working with Discourse I was surprised when you requested to create /var/discourse in my Docker host, it isn't the docker way but  but I trusted you.

I worked for a week (content, setup, personalized texts ...) in my development environment and today I wanted to verify the phone view then I stopped my VM, I added a bridge and after to restart my setup was not functional, then I logged in my VM, in nothing in /var/discourse except the shared folder containing just empty folders.

Googling I found ["Since Docker Machine (ex boot2docker) does (mostly) not persist changes in the VM file system, a Discourse installation is easily broken when the VM is restarted"](https://gist.github.com/fbender/67b99612cf83130e0a2e)

I think I lost all my work, for you I have 2 recommendations:

1. I know that Discourse is application-centric but if you have a Discourse-docker it supposed to work with docker standard technologies, then try to do it in the docker way or use [habitad](https://blog.chef.io/2016/06/14/introducing-habitat/) deploying docker containers.
1. Please add a big Warning in your readme file, I doesn't want other people getting his data lost after tons of work.

Thanks for your work, Discourse is amazing but ... yes, shit happen :'(

**Comment by xfalcox** [comment]
Sorry to hear that, this really sucks.

We recommend developing on either a [Vagrant VM](https://github.com/discourse/discourse/blob/master/docs/VAGRANT.md) or Native on [OSX](https://github.com/discourse/discourse/blob/master/docs/DEVELOPMENT-OSX-NATIVE.md) or [Ubuntu](https://github.com/discourse/discourse/blob/master/docs/DEVELOPER-ADVANCED.md).

However some [work is being done](https://github.com/discourse/discourse_docker/pull/292) to support development on Docker.
