### ISSUE TITLE
Official repo image broken

### ISSUE THREAD

**Issue by dukeofgaming** [discourse/discourse_docker#289]
Hi,

I have just installed the newest version of the Docker Toolbox for Windows, and when trying to pull the Discourse image I get this:

`PS H:\Program Files\Docker Toolbox> docker pull discourse/discourse:1.3.6
Warning: failed to get default registry endpoint from daemon (Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.21)). Using system default: https://index.docker.io/v1/
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.21)`

Also, no "latest" tag is pushed.

**Comment by SamSaffron** [comment]
This is clearly a docker install issue... 

recommend you raise it on https://forums.docker.com/ in the docker for windows category
