### ISSUE TITLE
run_bootstrap doesn't respect docker_args

### ISSUE THREAD

**Issue by liclac** [discourse/discourse_docker#291]
The `docker_args` option in container configurations is only read in `run_start`, not in `run_bootstrap`. This is inconsistent with the `--docker-args` flag (`$user_args`), which is applied universally.

**Comment by SamSaffron** [comment]
Sure, open to a PR that fixes this

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
