### ISSUE TITLE
discourse-setup: Using snippet in /etc/sysctl.d would be better in the long run

### ISSUE THREAD

**Issue by pmattern** [discourse/discourse_docker#294]
As of systemd 207 `systemd-sysctl`, which is in charge of setting sysctl parameters at boot time on most Linux systems these days, does by default no longer consider `/etc/sysctl.conf` but snippets `/etc/sysctl.d/*.conf` only, see section "CHANGES WITH 207" in file [NEWS](https://github.com/systemd/systemd/blob/master/NEWS). With regards to backwards compatibility a symbolic link `/etc/sysctl.d/99-sysctl.conf` pointing to `/etc/sysctl.conf` is recommended and currently implemented by Debian testing, Ubuntu 16.04, Fedora Rawhide and openSUSE Tumbleweed (while missing in Arch Linux). Yet this is rather some kind of workaround and I think it would make sense to have `discourse-setup` write a snippet `/etc/sysctl.d/NN-*.conf` in the long run.

**Comment by xfalcox** [comment]
Are you talking about this: https://github.com/discourse/discourse_docker/blob/master/discourse-setup#L93 ?

**Comment by pmattern** [comment]
Yes, that is what I was talking about.
Exchanging that line with e. g.
`echo 'vm.swappiness = 10' > /etc/sysctl.d/10-discourse-swap.conf`
yields the behavior I'd deem reasonable. This wouldn't check whether directory `/etc/sysctl.d/` preexists which can be assumed on all Linux systems right now, though.

**Comment by SamSaffron** [comment]
sure, @xfalcox  can you take this?

**Comment by xfalcox** [comment]
OK, looks like the correct is using `30-something` per README on `sysctl.d` and looking trough PostgreSQL and Jetbrains installs.

Please check #331 @pmattern and @SamSaffron

**Comment by pmattern** [comment]
#331 is behaving as I think it should do.
Not sure about number `30`, but I for one haven't found a set of decisive rules how to assign those numbers so far and I figure it's not too likely other configuration files `NN-foo.conf` with NN>30 tweaking this parameter will be around most of the time.

While at it let me mention that I'd be curious about your thoughts on https://github.com/discourse/discourse_docker/issues/295#issuecomment-258646245.
Tbh. I still find it hard to believe that it doesn't matter when invoking `discourse-setup` with locales other than English results in totally insufficient swap.
