### ISSUE TITLE
discourse-setup: Faulty handling of swap on hosts with non-English locale

### ISSUE THREAD

**Issue by pmattern** [discourse/discourse_docker#295]
Running `discourse-setup` on hosts with non-English locales may trigger faulty handling of swap on the host.

E. g. when it's launched on a system using `de_DE.UTF-8` there's
```
# ./discourse-setup 
which: no docker.io in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no docker.io in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
./discourse-setup: Zeile 37: [: : Ganzzahliger Ausdruck erwartet.
./discourse-setup: Zeile 46: [: : Ganzzahliger Ausdruck erwartet.
./discourse-setup: Zeile 162: netstat: Kommando nicht gefunden.
./discourse-setup: Zeile 162: netstat: Kommando nicht gefunden.
Ports 80 and 443 are free for use
[...]
```
where "Zeile" translates to "line", "Ganzzahliger Ausdruck erwartet." to "Expecting integer value." and "Kommando nicht gefunden." to "Command not found." After setting locale `C` there's
```
# ./discourse-setup 
which: no docker.io in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no docker.io in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
WARNING: Discourse requires at least 2GB of swap when running with 2GB of RAM
or less. This system does not appear to have sufficient swap space.

Without sufficient swap space, your site may not work properly, and future
upgrades of Discourse may not complete successfully.

ENTER to create a 2GB swapfile now, or Ctrl+C to exit
2097152+0 records in
2097152+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 20.8436 s, 103 MB/s
Setting up swapspace version 1, size = 2 GiB (2147479552 bytes)
no label, UUID=0aad98ae-e43b-4d84-8ade-5cbc2100319c
/swapfile       swap    swap    auto      0       0
vm.swappiness = 10
vm.swappiness = 10
./discourse-setup: line 162: netstat: command not found
./discourse-setup: line 162: netstat: command not found
Ports 80 and 443 are free for use
[...]
```

Similar findings are made with French. The character encoding doesn't seem to matter as the findings are the same with e. g. `de_DE{UTF-8,iso88591}` while the problem cannot be seen with `en_US{UTF-8,iso88591}`.

Seen running c857317 on Arch Linux x86_64, hence Docker 1.12.1.

**Comment by xfalcox** [comment]
Hello @pmattern,

the discourse-setup script is aimed for non-power users following our install script on Digital Ocean.

I don't see we making it compatible with all languagues. However you can open a PR for it.

**Comment by pmattern** [comment]
> the discourse-setup script is aimed for non-power users *following our install script* on Digital Ocean.

Not following. The [guide](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) to install on DigitalOcean is stating `discourse-setup` itself as the only script involved.
Did you by any chance mean "following our install guide" or so?

> I don't see we making it compatible with all languages.

You do realize that all languages except English seem to be affected? The said [INSTALL-cloud.md](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) states
> We recommend DigitalOcean, but these steps will work on any Docker-compatible cloud provider or local server.

But this does very well cover locales other than English, doesn't it? Also, the discussion in #194 strongly suggests locales other than English are not considered as insignificant as you say.

All in all it seems pretty implausible when you say totally insufficient swap space due to the conditions depicted above is something that should just be accepted, in particular considering the [remarkable amount](https://meta.discourse.org/t/create-a-swapfile-for-your-linux-server/13880) of swap space which is recommended.
