### ISSUE TITLE
reconfigure a container without re-building everything?

### ISSUE THREAD

**Issue by freeman-endlessm** [discourse/discourse_docker#300]
My apologies, I'm new to docker, but is there a way to re-configure a container without rebuilding it?

For instance, say I wanted to setup a test instance of discourse running on a different domain for testing, then promote the exact container to a production domain by reconfiguring it?

When I run ./discourse-setup, the process seems to be updating the discourse code, and otherwise running lots of code unrelated to a simple config change.

**Comment by SamSaffron** [comment]
You can change ENV stuff without needing a full rebuild

./launcher destroy app
edit app.yml, changing stuff in ENV section
./launcher start app
