### ISSUE TITLE
Error response from daemon: Mounts denied when ./launcher bootstrap app

### ISSUE THREAD

**Issue by johanrydstrom** [discourse/discourse_docker#302]
On macOS Sierra 10.12 and Docker

> Version 1.12.2-beta28 (12906)
> Channel: Beta
>71c4a001c2

when I try to use the launcher to start discourse, I get something like:

> 17:48 $ sudo ./launcher bootstrap app
cd /pups && git pull && /pups/bin/pups --stdin
/usr/local/bin/docker: Error response from daemon: Mounts denied: er.com/docker-for-mac/osxfs/#namespaces for more info.
.
r/discourse/shared/standalone/log/var-log
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.dock.
62d2b0134e59d04b95430b8c3835906d03a87127283bc40e05fa5e47c4dad762
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one

It seems related to how volumes are mounted; docker is now configured to allow this list of directories to be "bind mounted" into Docker containers:

- /Users
- /Volumes
- /tmp
- /private

i.e. NOT `/var/discourse/...` which is mentioned in the `container/app.yml`.

I could make it work by changing volumes mount points to `/private/var/discourse/...`, maybe the template(s) should be changed accordingly? I haven't tested on other platforms so this solution might not work for all.

**Comment by xfalcox** [comment]
The `launcher` script if for running docker in production, which usually means a Linux server as root.

For development we usually recommend this: https://github.com/discourse/discourse/blob/master/docs/DEVELOPMENT-OSX-NATIVE.md
