### ISSUE TITLE
Tag 1.3.7 not found in repository docker.io/discourse/discourse

### ISSUE THREAD

**Issue by reustonium** [discourse/discourse_docker#304]
Running discourse docker on a digtial ocean droplet, began troubleshooting a 502 bad gateway error and ran `./launcher rebuild app`

**Expected Behavior**
Discourse to grab latest discourse-docker image and rebuild the application

**Actual Behavior**

    WARNING: We are about to start downloading the Discourse base image
    This process may take anywhere between a few minutes to an hour, depending on your network speed
    
    Please be patient
    
    Unable to find image 'discourse/discourse:1.3.7' locally
    1.3.7: Pulling from discourse/discourse
    e9d5dc9fc926: Pulling fs layer
    45ca71ffb140: Pulling fs layer
    e9d5dc9fc926: Verifying Checksum
    e9d5dc9fc926: Download complete
    45ca71ffb140: Verifying Checksum
    45ca71ffb140: Download complete
    Pulling repository docker.io/discourse/discourse
    Tag 1.3.7 not found in repository docker.io/discourse/discourse
    Your Docker installation is not working correctly

**Comment by xfalcox** [comment]
The 1.3.7 image is here: https://hub.docker.com/r/discourse/discourse/tags/

The error still happens for you?

**Comment by reustonium** [comment]
I rebooted the server and re-ran `./launcher rebuild app` and it was able to complete the build no problem.  Not sure I can explain the previous behavior.  Thanks.
