### ISSUE TITLE
Ready to use docker image ?

### ISSUE THREAD

**Issue by backnight** [discourse/discourse_docker#307]
Hello,

I would like to know if there is a "ready to use" docker image of Discourse which can be configured by ENV vars (without need to ssh and run a ./discourse-setup command, etc) ?

I checked the main Dockerfile of Discourse (https://github.com/discourse/discourse_docker/blob/master/image/discourse/Dockerfile) and the port 80 is not even exposed... there is no entrypoint... it's not a "real dockerization" of Discourse in fact.

**Comment by SamSaffron** [comment]
just bootstrap one yourself and push it somewhere.
