### ISSUE TITLE
Postgresql might need much longer than 5 seconds to start up

### ISSUE THREAD

**Issue by hyperknot** [discourse/discourse_docker#309]
Postgresql startup wait is hard coded to 5 seconds:
https://github.com/discourse/discourse_docker/blob/aab5d67efdbeb3d79962276ba76e483f90d9679a/templates/postgres.template.yml#L224

In case the database wasn't shut down cleanly, this is not enough. An auto-recovery might take much longer than that. This is the core of the bug I've run into here:
https://meta.discourse.org/t/fatal-the-database-system-is-starting-up/52806/4

I believe the only way to wait for a clean postgres startup is something like this:

```
until su - postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl status -D /data/pgsql/9.5' | grep 'pg_ctl: server is running '
do
    echo
    echo "....waiting for PostgreSQL to start"
    sleep 1
done
sleep 3
echo "PostgreSQL started"
```

I don't know how can something like this implemented in the yml files, but this is the only bug-free way to do it.

**Comment by SamSaffron** [comment]
Sure, I am open to a PR that implements something like that, care to give it a shot?

**Comment by hyperknot** [comment]
I can only imagine this as a wait_for_postgres_startup.sh and a call to that in yml, does that sound reasonable to you?

**Comment by xfalcox** [comment]
@hyperknot can you test if #324 solves this problem?
