### ISSUE TITLE
docker-setup regex wrong

### ISSUE THREAD

**Issue by hyperknot** [discourse/discourse_docker#310]
The regex which should filter out devicemapper, etc. does not work.

It's actually allowing almost everything, as `[aufs|btrfs|zfs|overlay]` actually matches a single character in the list `aufs|btrzovely`.

My idea would be to use something like this:
```
test=`$docker_path info 2> /dev/null | grep 'Storage Driver: '`
if [[ "$test" =~ "Storage\ Driver:\ (aufs|btrfs|zfs|overlay)" ]]
```

Somehow this didn't work, although regex101.com says it should work.

Without grep storage driver it'd output 3 lines:
```
Storage Driver: devicemapper
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

**Comment by SamSaffron** [comment]
sure, can you submit a PR to fix @mpalmer your bash-fu is better is this issue legit?

**Comment by mpalmer** [comment]
Aaaah, the ol' "square brackets are not parentheses" bug... not the first time I've seen it, and probably not the last.  I'm not sure why your alternative doesn't work, @hyperknot; `bash` is *supposed* to support POSIX extended regular expressions (which is where the `(...|...)` syntax comes from), but :man_shrugging:.

I think what I'll do is just put the entire test into one big `grep`.  PR will arrive shortly.

**Comment by mpalmer** [comment]
PR #332 addresses this.
