### ISSUE TITLE
Bootstrap failure: can't cd to /plugins

### ISSUE THREAD

**Issue by twlz0ne** [discourse/discourse_docker#326]
Configuration

<pre>
root@vps:/var/discourse# cat containers/app.yml
...
hooks:
after_code:
    - exec:
        cd: $home/plugins
        cmd:
        - git clone https://github.com/discourse/docker_manager.git
...
</pre>

Bootstrap

<pre>
root@vps:/var/discourse# ./launcher bootstrap app
...
<b>sh: 1: cd: can't cd to /plugins</b>
...
FAILED
--------------------
Pups::ExecError: cd /plugins && git clone https://github.com/discourse/docker_manager.git failed with return #<Process::Status: pid 256 exit 2>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params {<b>"cd"=>"/plugins"</b>, "cmd"=>["git clone https://github.com/discourse/docker_manager.git"]}
2681d84b0139d7678da34d437837242e20b403d854b1016e53bb46b0766b4801
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
...
</pre>

Variable `$home` is empty, is this a problem?

The full log is here: http://pastebin.com/58dFcMBH

**Comment by twlz0ne** [comment]
Fixed:

    $ perl -p -i -e 's|cd: \$home/plugins|cd: /var/www/discourse/plugins|' container/app.yml

Following are the origin configurations:

<pre>
root@vps:/var/discourse# grep -vE '[ ]*#.*' containers/app.yml
templates:
    - "templates/postgres.template.yml"
    - "templates/redis.template.yml"
    - "templates/web.template.yml"
    - "templates/web.ratelimited.template.yml"

expose:
    - "80:80"
    - "2222:22"

params:
    db_default_text_search_config: "pg_catalog.english"
    db_shared_buffer: "256M"
    db_work_mem: "40MB"

env:
    LANG: en_US.UTF-8
    UNICORN_WORKERS: 2
    DISCOURSE_HOSTNAME: '{HOSTNAME}'
    DISCOURSE_DEVELOPER_EMAILS: '{EMAIL}'
    DISCOURSE_SMTP_ADDRESS: 'smtp.exmail.qq.com'
    DISCOURSE_SMTP_PORT: 587
    DISCOURSE_SMTP_USER_NAME: '{EMAIL}'
    DISCOURSE_SMTP_PASSWORD: '{PASSWORD}'
    DISCOURSE_SMTP_AUTHENTICATION: login
    DISCOURSE_SMTP_OPENSSL_VERIFY_MODE: none
    DISCOURSE_SMTP_START_TLS: true

volumes:
    - volume:
        host: /var/discourse/shared/standalone
        guest: /shared
    - volume:
        host: /var/discourse/shared/standalone/log/var-log
        guest: /var/log

hooks:
    after_code:
    - exec:
        <b>cd: $home/plugins</b>
        cmd:
            - git clone https://github.com/discourse/docker_manager.git

run:
    - exec: echo "Beginning of custom commands"
    - exec: echo "End of custom commands"
</pre>

**Comment by SamSaffron** [comment]
Sorry, this is the wrong spot for support, can you try https://meta.discourse.org
