### ISSUE TITLE
boot script does not reap zombie processes

### ISSUE THREAD

**Issue by mitar** [discourse/discourse_docker#328]
I was looking at a bash-only init script for my runit docker image and I found [your script](https://github.com/discourse/discourse_docker/blob/master/image/base/boot). But when comparing with other non-bash implementations I think (and I might be mistaken, this is just based on looking at the code, not reproducing it myself) the boot script does not reap zombies.

When a process has PID 1 all orphan processes are re-parented to it. When this orphan process finishes, a SIGCHLD is sent to the parent process (PID 1, in this case boot script) which should call `wait` to clean it. boot script does not seem to be doing this. So zombie processes are pilling up until they are cleaned at the stop of the container.

I think this could be addressed by explicitly setting SIGCHLD handler to ignore (SIG_IGN). It has to be set explicitly, even if ignore is already the default.

Background: https://en.wikipedia.org/wiki/Child_process

**Comment by SamSaffron** [comment]
I am sorry, are you reporting a particular issue you are having? runsvdir is taking care of the bulk of process management here, this is simply a wrapper to translate some signals and handle a few tiny edge cases.

**Comment by mitar** [comment]
The problem is, that because `runsvdir` is not PID 1 anymore, because you have this wrapper, `runsvdir` cannot handle the "bulk of process management here" because OS does not re-parent the orphan process under `runsvdir`, but under PID 1, in this case this wrapper script. When this orphan process dies, a SIGCHLD is sent to the parent process (this wrapper script), but the wrapper script does not do anything about it, so the process becomes a zombie process.

You have two options:
* handle the SIGCHLD in the wrapper script (pretty easy, handle the SIGCHLD signal, or explicitly set handling to ignore)
* instruct OS to parent orphan processes under `runsvdir` (making `runsvdir` a [subreaper](https://unix.stackexchange.com/questions/250153/what-is-a-subreaper-process)), working only on Linux >= 3.4

**Comment by SamSaffron** [comment]
sure a PR to have it handle SIGCHLD is fine, feel free to submit it.
