### ISSUE TITLE
docker_args for build time

### ISSUE THREAD

**Issue by zh99998** [discourse/discourse_docker#337]
currently docker_args is only enabled in runtime, but sometimes need extra argument on build

for example, my postgres and redis in a docker `network`. and I need a `--network=<my_network>` argument for a container to access the database.

**Comment by SamSaffron** [comment]
Sure, I think docker_args should be enabled at bootstrap as well, can you submit a PR ?

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
