### ISSUE TITLE
image problems

### ISSUE THREAD

**Issue by saschaarthur** [discourse/discourse_docker#345]
Hello,

Im using this discourse docker container more or less with default settings.

We running into the trouble that our previews(attached images) in the topics are not working properly.

I investigates a bit deeper and it seems that the html generator is not detecting the size of the image correctly:
`
<img src="xxx/uploads/default/original/1X/e21fa533c8b576334ce47208b471eb0676be4420.png" width="0" height="0">`

The webserver itself returns the image correctly and if i live resize the html tag (with debug console), the image shows up.

This issues seems also only to happen in google chrome (latest version) firefox is working fine. Any idears?

Also if we edit the topic, the preview sizes in the html tag are correct..

**Comment by ZogStriP** [comment]
This is something for https://meta.discourse.org.
