### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by CGM-Face** [discourse/discourse_docker#346]
Hi,

you have a syntaxerror in line 195 in the discourse-setup.

./discourse-setup: Zeile 195: 256 *  : Syntax Fehler: Operator erwartet. (Fehlerverursachendes Zeichen ist »*  «).

**Comment by OXIDFabian** [comment]
Hi,
i had to same issue.
I fixed this problem by changing line 93
from
echo `free -g --si | awk ' /Mem:/  {print $2} '`  
to  
echo `awk '{ printf "%.f", $2/1024/1024 ; exit}' /proc/meminfo`

**Comment by SamSaffron** [comment]
@soulshake, while you are swimming in launcher bash script can you have a quick look at this?

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
