### ISSUE TITLE
Have you considered Alpine instead of Ubuntu base

### ISSUE THREAD

**Issue by abshkd** [discourse/discourse_docker#364]
Is there anyway we could use Alpine as base image? Is Ubuntu really necessary?
Reason I ask is because it would make for much smaller images, Alpine is only 5MB. 

For e.g. https://hub.docker.com/r/centurylink/alpine-rails/~/dockerfile/

**Comment by envygeeks** [comment]
https://github.com/cowboyd/therubyracer/issues/378

**Comment by xfalcox** [comment]
Well, a fork with an working alpine image that passes all tests is welcome.

**Comment by envygeeks** [comment]
I like how you handle tickets and open discussions: Not all, why bother? Right? Lets just close tickets and pass the buck,

**Comment by jomaxro** [comment]
@envygeeks, we don't use the GitHub Issue tracker for discussion about Discourse. Issues was unintentionally left enabled on some public repos, and we're working on closing the issues and removing the issue tracker. Please visit meta.discourse.org to discuss the Discourse Docker base image.
