### ISSUE TITLE
discourse-setup incorrectly relies on "addr:" in ipconfig output

### ISSUE THREAD

**Issue by tomreyn** [discourse/discourse_docker#373]
On a Debian GNU/Linux 9.0 "stretch" VM runing in a KVM environment, the output of the _ipconfig_ command does not return a string containing a pattern such as

> inet addr:123.123.123.123

but just 

> inet 123.123.123.123

As a result, _discourse-setup_ sets the IP variable to an empty string and the installation fails with

> mydomain.net does not appear to resolve to .

A better approach would be to use something similar to 

```
ip -f inet addr show $IFACE | grep -Po 'inet \K[\d.]+' | head -n1
```

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
