### ISSUE TITLE
discourse-setup makes sed parse SMTP password

### ISSUE THREAD

**Issue by tomreyn** [discourse/discourse_docker#374]
discourse-setup uses sed to place the user provided SMTP password in the configuration file. The user input is used as a regular expression by sed (-e) there, while it is really just a plain text string. 

This works as long as the password does not contain any special characters which sed would parse. 

When it fails to work, the user may get to see a sed error message in the _discourse-setup_ output, and installation may fail. 

This is possibly a security issue, since sed might end up executing the input string (///e).

**Comment by jomaxro** [comment]
We don't use the GitHub Issue tracker for discussion about Discourse. Please visit meta.discourse.org to discuss the Discourse Docker base image.
