### ISSUE TITLE
Preview pane uses local docker container IP address

### ISSUE THREAD

**Issue by hassanfarid** [discourse/discourse_docker#375]
It looks like the preview pane when creating a new topic is broken. Inspecting via the browser console says the markdown-it-bundle...js script fails to load because of a timed out connection. Unlike other assets, this is being looked up through the IP address rather than the domain name: http://172.17.0.5/assets/markdown-it-bundle-fb0211dacd14c5223c2336cabe82bfaf9cf84e82cb3f328ff2d8a216d1d89fa9.js

I’d guess this is failing because the URL needs a port number if using the IP address.

Deployment Information:
I am using a single node docker deployment of discourse. I have set these 3 variables in container/app.yml
 1. DISCOURSE_HOSTNAME: sub.domain.com
 2. DISCOURSE_HOST_IP: {docker-host-IP}
 3. DOCKER_USE_HOSTNAME: true

**Comment by jomaxro** [comment]
We do not provide support on GIthub. Please visit https://meta.discourse.org for support.
