### ISSUE TITLE
Migration directions (or backup directions) to move from one server to another.

### ISSUE THREAD

**Issue by bbarker** [discourse/discourse_docker#376]
I'd like to use `discourse_docker` for a new installation of discourse - this would be great, since I don't have to worry about which provider I'm using and could easily switch from one VM to another with a simple rsync and docker image rebuild (I presume). Before going down that route, I want to make sure that's actually the case - could you post directions for doing so?

Thanks,

**Comment by jomaxro** [comment]
Hi @bbarker, we don't provide support on Github. Please take a look at [meta.discourse.org](https://meta.discourse.org) where we have numerous guides, and ask a question there if you cannot find the answer.
