### ISSUE TITLE
Missing dirs inside container

### ISSUE THREAD

**Issue by modules-io** [discourse/discourse_docker#49]
Ubuntu trusty, latest docker git, standalone.yml as containers/app.yml. No changes.

Bootstrap succeeds in building the image, but when running it whines about missing dirs:

    Missing privilege separation directory: /var/run/sshd
    2014-05-21 00:10:49 UTC FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory

Bad mounts? I'd ssh in the thing to try to figure out what's missing but, as above, sshd won't even start due to the missing dirs.

Here's the container config for reference. Looks otherwise ok.

[{
    "ID": "c7ba6066d208ab1dd60e67945be6527c15a699a5eee5af4a4864199bf8312f4e",
    "Created": "2014-05-21T00:10:47.98572045Z",
    "Path": "/usr/bin/runsvdir",
    "Args": [
        "-P",
        "/etc/service"
    ],
    "Config": {
        "Hostname": "server1-app",
        "Domainname": "",
        "User": "",
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "22/tcp": {},
            "80/tcp": {}
        },
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": [
            "HOME=/root",
            "RAILS_ENV=production",
            "UNICORN_WORKERS=3",
            "UNICORN_SIDEKIQS=1",
            "RUBY_GC_MALLOC_LIMIT=40000000",
            "RUBY_HEAP_MIN_SLOTS=800000",
            "DISCOURSE_DB_SOCKET=/var/run/postgresql",
            "DISCOURSE_DB_HOST=",
            "DISCOURSE_DB_PORT=",
            "DISCOURSE_DEVELOPER_EMAILS=my-email-address@example.com",
            "DISCOURSE_HOSTNAME=discourse.example.com",
            "DISCOURSE_SMTP_ADDRESS=smtp.example.com",
            "DOCKER_HOST_IP=172.17.42.1",
            "SSH_PUB_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGVDleXHygByPmIfmS32f8bBR6+iezlVK0IAIf8GqZiPDZ0mv/qiK5vwWAaKKO17y/goEfK+PpHZkvvjCx1pBNrkNrWJR6r3FubDqGjWo4w5yYvvO7kYKGavrQjfrd+TTxbHAVHTGOMdwLEY5yuKz/g3rkVihVensarZYzWggozTJdvXvO8N/qlvdFc9aRsGOPsbejUgNr1bcqFW5W9G825JdMAshkn1xc5h/d6pmfMWcqmnaURfr4nA2Up41OR4/xNCCHxonxs8CU58XE4nOW13g5yuk1GIhW70Ftk9GYobMpvltfO1KAKzuuMydw6hufAFJiwip4o3s0MhIy0KOF m@server1",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/usr/bin/runsvdir",
            "-P",
            "/etc/service"
        ],
        "Image": "local_discourse/app",
        "Volumes": {
            "/shared": {}
        },
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "OnBuild": null
    },
    "State": {
        "Running": true,
        "Pid": 9191,
        "ExitCode": 0,
        "StartedAt": "2014-05-21T00:10:48.07658237Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "d1eb53a56d661786b82169c9b81904bb09c177cb627d90057ec95aa5a78e8c4f",
    "NetworkSettings": {
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "Gateway": "172.17.42.1",
        "Bridge": "docker0",
        "PortMapping": null,
        "Ports": {
            "22/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "2222"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "80"
                }
            ]
        }
    },
    "ResolvConfPath": "/etc/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/c7ba6066d208ab1dd60e67945be6527c15a699a5eee5af4a4864199bf8312f4e/hostname",
    "HostsPath": "/var/lib/docker/containers/c7ba6066d208ab1dd60e67945be6527c15a699a5eee5af4a4864199bf8312f4e/hosts",
    "Name": "/app",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/shared": "/var/docker/shared/standalone"
    },
    "VolumesRW": {
        "/shared": true
    },
    "HostConfig": {
        "Binds": [
            "/var/docker/shared/standalone:/shared"
        ],
        "ContainerIDFile": "cids/app.cid",
        "LxcConf": [],
        "Privileged": false,
        "PortBindings": {
            "22/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "2222"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "80"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "VolumesFrom": null,
        "NetworkMode": "bridge"
    }
}]

**Comment by SamSaffron** [comment]
this is ancient, assuming its been sorted.
