### ISSUE TITLE
How to install Discourse with a remote PostgreSQL database?

### ISSUE THREAD

**Issue by migurski** [discourse/discourse_docker#57]
I’m trying to install Discourse so that it will use an external Postgres host, using a set of Ubuntu instructions from [howtoinstalldiscourse.com](http://www.howtoinstalldiscourse.com/how-to-install-discourse-on-ubuntu/). I've copied the [_standalone.yml_ config](https://github.com/discourse/discourse_docker/blob/f0033c25b315732da8596a7c514c1af7d977ceeb/samples/standalone.yml), removed _postgres.template.yml_, and added [DB details back to the environment section](https://github.com/discourse/discourse_docker/blob/88126ebabad600d454b3cc2b0ea977fa14046a61/samples/web_only.yml#L19). Bootstrapping fails at the `db:migrate` step, and there are suspiciously fewer DB details than I'd expect, such as no database or user name.

Am I attempting something that should work? How can I create a Discourse instance that uses an external database server instead of a built-in one?

Complete configuration below.

    ##
    ## After making changes to this file, you MUST rebuild for any changes
    ## to take effect in your live Discourse instance:
    ## 
    ## /var/docker/launcher rebuild app
    ##

    ## this is the all-in-one, standalone Discourse Docker container template
    templates:
      - "templates/cron.template.yml"
      - "templates/redis.template.yml"
      - "templates/sshd.template.yml"
      - "templates/web.template.yml"

    ## which TCP/IP ports should this container expose?
    expose:
      - "80:80"   # fwd host port 80   to container port 80 (http)
      - "2222:22" # fwd host port 2222 to container port 22 (ssh)

    params:
      ## Which Git revision should this container use?
      version: HEAD

    env:
      ## The database part
      DISCOURSE_DB_SOCKET: ''
      DISCOURSE_DB_PASSWORD: 'discourse'
      DISCOURSE_DB_HOST: 'discourse@hostname.example.com:5432'
      ## How many concurrent web requests are supported?
      ## With 2GB we recommend 3-4 workers, with 1GB only 2
      # UNICORN_WORKERS: 3
      ##
      ## List of comma delimited emails that will be made admin on signup
      DISCOURSE_DEVELOPER_EMAILS: '___________'
      ##
      ## The domain name this Discourse instance will respond to
      DISCOURSE_HOSTNAME: 'discourse.example.com'
      ##
      ## The mailserver this Discourse instance will use
      DISCOURSE_SMTP_ADDRESS: ________________          # (mandatory)
      # DISCOURSE_SMTP_PORT: 587                        # (optional)
      DISCOURSE_SMTP_USER_NAME: __________________      # (optional)
      DISCOURSE_SMTP_PASSWORD: __________               # (optional)
      ##
      ## the origin pull CDN address for this Discourse instance
      # DISCOURSE_CDN_URL: //discourse-cdn.example.com

    ## These containers are stateless, all data is stored in /shared
    volumes:
      - volume:
          host: /var/docker/shared/standalone
          guest: /shared

    ## The docker manager plugin allows you to one-click upgrade Discouse
    ## http://discourse.example.com/admin/docker
    hooks:
      after_code:
        - exec:
            cd: $home/plugins
            cmd:
              - mkdir -p plugins
              - git clone https://github.com/discourse/docker_manager.git

    ## Remember, this is YAML syntax - you can only have one block with a name
    run:
      - exec: echo "Beginning of custom commands"

      ## If you want to configure password login for root, uncomment and change:
      #- exec: apt-get -y install whois # for mkpasswd
      ## Use only one of the following lines:
      #- exec: /usr/sbin/usermod -p 'PASSWORD_HASH' root
      #- exec: /usr/sbin/usermod -p "$(mkpasswd -m sha-256 'RAW_PASSWORD')" root

      ## If you want to authorized additional users, uncomment and change:
      #- exec: ssh-import-id username
      #- exec: ssh-import-id anotherusername

      - exec: echo "End of custom commands"
      - exec: awk -F\# '{print $1;}' ~/.ssh/authorized_keys | awk 'BEGIN { print "Authorized SSH keys for this container:"; } NF>=2 {print $NF;}'

**Comment by SamSaffron** [comment]
This is a general support issue, belongs on https://meta.discourse.org
