### ISSUE TITLE
SSH autoconfiguration does not work

### ISSUE THREAD

**Issue by robotlovesyou** [discourse/discourse_docker#61]
I've tried every option offered in app.yaml. I've tried adding extra ssh users and I've tried adding explicit passwords but no matter what I do the ssh asks for the users password and does not accept the password I supplied to it in app.yaml

**Comment by rata** [comment]
the ssh config has an option to only allow root login without-password. That was probably ir

**Comment by SamSaffron** [comment]
we ripped out sshd by default, it is not needed with docker exec anyway
