### ISSUE TITLE
Need a proxy instruction for GIT

### ISSUE THREAD

**Issue by redlabo** [discourse/discourse_docker#79]
Hi,

I tried Discourse behind an enterprise proxy, so I set the proxy in /etc/default/docker. But no result, git could'nt pull anything, I proceeded to insert a proxy variable HTTP_PROXY in containers/app.yml. No more luck.
Finally, I figured out to insert a git config in launcher at this line

```
(exec echo "$input" | $docker_path run "${env[@]}" -e DOCKER_HOST_IP=$docker_ip --cidfile $cidbootstrap -i -a stdin -a stdout -a stderr $volumes $image \
/bin/bash -c "git config --global http.proxy http://x.x.x.x:3128/;$run_command") \
|| ($docker_path rm cat $cidbootstrap && rm $cidbootstrap)
This time the pull process from git succeeded. In fact, I was obliged to insert this too in run_command="cd /pups &&"
  if [[ ! "false" =  $update_pups ]]; then
    run_command="$run_command git config --global http.proxy http://x.x.x.x:3128/ && git pull &&"
  fi
```

I worked on the commit 97dd1ad146de58147d4e2f40e502b277e3ebc62c.
In fact after commenting out HTTP_PROXY, it appeared that gem needs this too.
Have a nice day.

**Comment by SamSaffron** [comment]
totally stale, unclear if this is even still an issue, closing
