### ISSUE TITLE
"Could not resolve host: github.com"

### ISSUE THREAD

**Issue by Peeja** [discourse/discourse_docker#85]
I'm following the [Digital Ocean instructions](https://github.com/discourse/discourse/blob/master/docs/INSTALL-digital-ocean.md). When I get to the bootstrap step (`./launcher bootstrap app`), it fails with

```
cd /pups && git pull && /pups/bin/pups --stdin
fatal: unable to access 'https://github.com/SamSaffron/pups.git/': Could not resolve host: github.com
```

It sounds like DNS isn't available within the container. Any idea what's going on? Did I do something wrong, or is there a mistake in the instructions?

**Comment by saothienhat** [comment]
I use the Window. Where should I do to fix this issue ?

**Comment by SamSaffron** [comment]
@saothienhat not sure general support really should go on https://meta.discourse.org

**Comment by naggie** [comment]
It happened a second time for me. I noticed our Gravatars wouldn't manually refresh. I then checked the dashboard by chance and saw sidekiq was not running. I had to rebuild the app, removing all images to be sure.
